% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={homework02},
  pdfauthor={zhewei xie},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{homework02}
\author{zhewei xie}
\date{2024-07-23}

\begin{document}
\maketitle

\hypertarget{problem-1-capital-metro-ut-ridership}{%
\section{Problem 1: Capital Metro UT
Ridership}\label{problem-1-capital-metro-ut-ridership}}

\hypertarget{question-1}{%
\subsection{Question 1}\label{question-1}}

\includegraphics{homework02_files/figure-latex/problem1_a-1.pdf}

\hypertarget{question-2}{%
\subsection{Question 2}\label{question-2}}

\includegraphics{homework02_files/figure-latex/problem1_b-1.pdf}

\newpage

\hypertarget{problem-2-wrangling-the-billboard-top-100}{%
\section{Problem 2: Wrangling the Billboard Top
100}\label{problem-2-wrangling-the-billboard-top-100}}

\hypertarget{part-a}{%
\subsection{Part A}\label{part-a}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.5000}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.4286}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.0714}}@{}}
\caption{The top 10 most popular songs since 1958, as measured by the
total number of weeks that a song spent on the Billboard Top
100.}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
performer
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
song
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
count
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
performer
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
song
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
count
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Imagine Dragons & Radioactive & 87 \\
AWOLNATION & Sail & 79 \\
The Weeknd & Blinding Lights & 76 \\
Jason Mraz & I'm Yours & 76 \\
LeAnn Rimes & How Do I Live & 69 \\
OneRepublic & Counting Stars & 68 \\
LMFAO Featuring Lauren Bennett \& GoonRock & Party Rock Anthem & 68 \\
Adele & Rolling In The Deep & 65 \\
Jewel & Foolish Games/You Were Meant For Me & 65 \\
Carrie Underwood & Before He Cheats & 64 \\
\end{longtable}

\newpage

\hypertarget{part-b}{%
\subsection{Part B}\label{part-b}}

\includegraphics{homework02_files/figure-latex/problem2_b-1.pdf}

\hypertarget{part-c}{%
\subsection{Part C}\label{part-c}}

\includegraphics{homework02_files/figure-latex/problem2_c-1.pdf}

\hypertarget{problem-3-regression-practice}{%
\section{Problem 3: regression
practice}\label{problem-3-regression-practice}}

\hypertarget{question-a}{%
\subsection{Question A}\label{question-a}}

\includegraphics{homework02_files/figure-latex/problem3_a_1-1.pdf}

\begin{longtable}[]{@{}lr@{}}
\caption{The fitted linear model parameters of
creatinine.}\tabularnewline
\toprule\noalign{}
& value \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
& value \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
intercept & 147.8129158 \\
slope & -0.6198159 \\
\end{longtable}

Based on the fitted linear regression model parameter, it is clear that
the linear regression is:

\(\text{Clearance}=147.8129158-0.6198159\cdot\text{Age}\).

\emph{Note: Based on the data from 18-year-old to 88-year-old.}

The linear regression gives the conditional expected value of creatinine
clearance rate, given someone's age.

So let's plug in \(\text{Age}=55\) into the fitted equation:

\(E(\text{Clearance}|Age=55)=147.8129158-0.6198159\cdot55=113.723\)

This is the exception of creatinine clearance rate for a 55-year-old,
with the value is 113.723 mL/minute.

\newpage

\hypertarget{question-b}{%
\subsection{Question B}\label{question-b}}

\begin{longtable}[]{@{}rrrrrrrr@{}}
\toprule\noalign{}
age & predicted & age & predicted & age & predicted & age & predicted \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
15 & 138.5157 & 34 & 126.7392 & 53 & 114.9627 & 72 & 103.18617 \\
16 & 137.8959 & 35 & 126.1194 & 54 & 114.3429 & 73 & 102.56636 \\
17 & 137.2760 & 36 & 125.4995 & 55 & 113.7230 & 74 & 101.94654 \\
18 & 136.6562 & 37 & 124.8797 & 56 & 113.1032 & 75 & 101.32673 \\
19 & 136.0364 & 38 & 124.2599 & 57 & 112.4834 & 76 & 100.70691 \\
20 & 135.4166 & 39 & 123.6401 & 58 & 111.8636 & 77 & 100.08710 \\
21 & 134.7968 & 40 & 123.0203 & 59 & 111.2438 & 78 & 99.46728 \\
22 & 134.1770 & 41 & 122.4005 & 60 & 110.6240 & 79 & 98.84746 \\
23 & 133.5572 & 42 & 121.7806 & 61 & 110.0041 & 80 & 98.22765 \\
24 & 132.9373 & 43 & 121.1608 & 62 & 109.3843 & 81 & 97.60783 \\
25 & 132.3175 & 44 & 120.5410 & 63 & 108.7645 & 82 & 96.98802 \\
26 & 131.6977 & 45 & 119.9212 & 64 & 108.1447 & 83 & 96.36820 \\
27 & 131.0779 & 46 & 119.3014 & 65 & 107.5249 & 84 & 95.74838 \\
28 & 130.4581 & 47 & 118.6816 & 66 & 106.9051 & 85 & 95.12857 \\
29 & 129.8383 & 48 & 118.0618 & 67 & 106.2853 & 86 & 94.50875 \\
30 & 129.2184 & 49 & 117.4419 & 68 & 105.6654 & 87 & 93.88894 \\
31 & 128.5986 & 50 & 116.8221 & 69 & 105.0456 & 88 & 93.26912 \\
32 & 127.9788 & 51 & 116.2023 & 70 & 104.4258 & 89 & 92.64930 \\
33 & 127.3590 & 52 & 115.5825 & 71 & 103.8060 & 90 & 92.02949 \\
\end{longtable}

Based on the linear regression, it says that a one-year change in age is
associated with a 0.6198159 mL/minute change in creatinine clearance
rate, on average.

\newpage

\hypertarget{question-c}{%
\subsection{Question C}\label{question-c}}

Based on the fitted linear regression:

\(\text{Clearance}=147.8129158-0.6198159\cdot\text{Age}\).

It is clear that
\(E(\text{Clearance}|Age=40)=147.8129158-0.6198159\cdot40=123.0203\)

and \(E(\text{Clearance}|Age=60)=147.8129158-0.6198159\cdot60=110.624\).

So for the 40-year-old,
\(\hat\varepsilon=y-\hat y=135-123.0203\approx12\),

while for the 60-year-old,
\(\hat\varepsilon=y-\hat y=112-110.624\approx1\).

Therefore, based on the differences, the 40-year-old is healthier for
the age.

\newpage

\hypertarget{problem-4-probability-practice}{%
\section{Problem 4: probability
practice}\label{problem-4-probability-practice}}

\hypertarget{part-a-1}{%
\subsection{Part A}\label{part-a-1}}

Event A is defined as `you will get at least one lemon among the 3 cars
you purchase.' It is easier to consider the converse: getting no lemons
among the 3 cars you purchase. To calculate this, you can imagine
choosing 3 cars from 20 normal cars, while the probability space
consists of choosing 3 cars from all 30 cars.

\(P(A)=1-P(\overline A)=1-\frac{\binom{20}{3}}{\binom{30}{3}}\approx0.719\)

\hypertarget{part-b-1}{%
\subsection{Part B}\label{part-b-1}}

\hypertarget{question-1-1}{%
\subsubsection{Question 1}\label{question-1-1}}

It is clear that:

\(\text{odd}+\text{even}=\text{odd}\\\text{odd}+\text{odd}=\text{even}\\\text{even}+\text{even}=\text{even}\)

so the numbers of a 1-6 dice could be split to 2 sets.

\(Set_{odd}=\{1, 3, 5\}\)

\(Set_{even}=\{2, 4, 6\}\)

Event A is `the sum of the two numbers is odd.' This event can be split
into two steps. Step 1 is to choose one odd number from the set of odd
numbers, and Step 2 is to choose one even number from the set of even
numbers. Interestingly, we could choose from the odd set first or the
even set first, and it does not affect the sum. Meanwhile, the
probability space is clearly the random selection of 2 numbers from 1 to
6.

\(P(A)=\frac{\binom{3}{1}\binom{3}{1}2!}{\binom{6}{2}}\)

\hypertarget{question-2-1}{%
\subsubsection{Question 2}\label{question-2-1}}

\(x+y\leq7\)

\begin{verbatim}
## Scale for x is already present.
## Adding another scale for x, which will replace the existing scale.
## Scale for y is already present.
## Adding another scale for y, which will replace the existing scale.
\end{verbatim}

\includegraphics{homework02_files/figure-latex/problem4_b_1-1.pdf}

\begin{verbatim}
## [1] 15
\end{verbatim}

Through counting the case, the probability that the sum of the two
numbers is less than 7 is \(\frac{15}{36}\).

\hypertarget{question-3}{%
\subsubsection{Question 3}\label{question-3}}

Event A is ``the sum of the two numbers is less than 7''.

Event B is ``the sum of the two numbers is odd''.

So \(P(A|B)=\frac{P(AB)}{P(B)}\).

Given that there are 6 cases where the sum of the two numbers is less
than 7 and odd, and there are 18 cases where the sum of the two numbers
is odd, the probability that the sum of the two numbers is less than 7,
given that it is odd, is \(\frac{6}{18}\).

\hypertarget{part-c-1}{%
\subsection{Part C}\label{part-c-1}}

Let's donate the event ``Random clicker'' as RC, the event ``Truth
clicker'' as TC, the event ``answer yes'' as Y, the event ``answer no''
as N.

\(P(Y)=P(Y|RC)\cdot P(RC)+P(Y|TC)\cdot P(TC)\)

Given the expected fraction of random clickers is 0.3, it means that
\(P(RC)=0.3\), so \(P(TC)=1-P(\overline {TC})=1-P(RC)=1-0.3=0.7\).

Besides, because random clickers would click either one with equal
probability, which means \(P(Y|RC)=P(N|RC)=0.5\) and the following
survey results: 65\% said Yes and 35\% said No.~

Therefore,
\(P(Y)=P(Y|RC)\cdot P(RC)+P(Y|TC)\cdot P(TC)=0.5\cdot0.3+P(Y|TC)\cdot0.7=0.65\),
it is clear that
\(P(Y|TC)=\frac{P(Y)-P(Y|RC)\cdot P(RC)}{P(TC)}=\frac{0.65-0.5\cdot0.3}{0.7}\approx0.714\).

\hypertarget{part-d}{%
\subsection{Part D}\label{part-d}}

Let's donate the event ``someone has the disease'' as D, the event
``test positive'' as TP.

Because someone has the disease, there is a probability of 0.993 that
they will test positive, it is clear that \(P(TP|D)=0.993\).

Additionally, if someone does not have the disease, there is a 0.9999
probability that they will test negative, which means
\(P(\overline {TP}|\overline D)=0.9999\) and
\(P(TP|\overline D)=1-P(\overline {TP}|\overline D)=0.0001\).

In the general population, incidence of the disease is reasonably rare:
about 0.0025\% of all people have it, which means \(P(D)=0.000025\) and
\(P(\overline D)=1-P(\overline D)=0.999975\).

\(P(TP)=P(TP|D)\cdot P(D)+P(TP|\overline D)\cdot P(\overline D)=0.993\cdot0.000025+0.0001\cdot0.999975=0.0001248225\)

According to Bayes' theorem,
\(P(D|TP)=\frac{P(TP|D)\cdot P(D)}{P(TP)}=\frac{0.993\cdot0.000025}{0.0001248225}\approx0.1989\).

\hypertarget{part-e}{%
\subsection{Part E}\label{part-e}}

Let's donate the event ``an aircraft is present in a certain area'' as
A, the event ``a radar correctly registers its presence'' as R.

\(P(R|A)=0.99\)\\
\(P(R|\overline A)=0.10\)\\
\(P(A)=0.05\) and \(P(\overline A)=1-P(A)=0.95\)

Because
\(P(R)=P(R|A)\cdot P(A)+P(R|\overline A)\cdot P(\overline A)=0.99\cdot0.05+0.10\cdot0.95=0.1445\).

According to Bayes' theorem,
\(P(A|R)=\frac{P(R|A)\cdot P(A)}{P(R)}=\frac{0.99\cdot0.05}{0.1445}\approx0.3426\)

\hypertarget{problem-5-modeling-soccer-games-with-the-poisson-distribution}{%
\section{Problem 5: modeling soccer games with the Poisson
distribution}\label{problem-5-modeling-soccer-games-with-the-poisson-distribution}}

\textbf{Question: }

What are the estimated probabilities of win, lose, and draw results for
a match between Liverpool (home) and Tottenham (away), and a match
between Manchester City (home) and Arsenal (away)?

\textbf{Approach: }

Step 1:

The article
\href{https://faculty.chicagobooth.edu/nicholas.polson/teaching/41000/speigelhalter-epl.pdf}{``One
match to go!'', by Spiegelhalter and Ng} provides an algorithm to
evaluate the `attack strength' and `defence weakness' of a team in a
season.

\(\text{Attack Strength}=\frac{\text{\‘goals for\’ of the team}}{\text{the average number of goals scored by a team}}\)

\(\text{Defence Weakness}=\frac{\text{\‘goals against\’ of the team}}{\text{the average number of goals scored by a team}}\)

To use this algorithm, let's define the `average number of goals scored
by a team' as \(\text{avg\_goals}\), the ``\,`goals against' of team i''
as \(\text{GF}_i\), and the ``\,`goals against' of team i'' as
\(\text{GA}_i\).

So, using the algorithm and data, we can calculate:

\(\text{avg\_goals}=\frac{\sum_{i=1}^{20}(\text{GF}_i+\text{GA}_i)}{20}=53.6\)

\emph{Note: 20 is the number of the teams of the League.}

By examining the data from `epl\_2018-19\_away.csv' and
`epl\_2018-19\_home.csv,' it is clear that the goals are categorized
into two classes: home team goals and away team goals. Therefore, the
following can be established:

\(\text{GF}=\text{GF}_{home}+\text{GF}_{away}\)

\(\text{GA}=\text{GA}_{home}+\text{GA}_{away}\)

\emph{Note: We should merge the two tables carefully because the order
of teams in the tables is different. We should merge them using the key
`Team.'}

After merging the two files by the key `Team' and summing the GF and GA
from the merged file, it is easy to use R to calculate each team's
`attack strength' and `defence weakness' with the appropriate function.

Step 2:

According to the article, it is also important to calculate the average
goals per game as a baseline, categorized by goals scored by the home
team and by the away team.

Since the attribute named `GP' stands for `games played,' it is clear
that each team played 19 games as the home team and 19 games as the away
team. Therefore, the total number of games is \(19\cdot20=380\).

Let's denote the `average goals scored by home teams' as
\(\text{avg\_goals\_per\_game}_{home}\), denote the ``average goals
scored by away team'' as \(\text{avg\_goals\_per\_game}_{away}\).

\(\text{GF}_i\) represent the `goals for' by team \(i\) as the home
team, while \(\text{GA}_i\) represents the `goals against' team \(i\) as
the home team''. Since each goal scored as `goals against' for a home
team is the same as `goals for' for the away team, it follows that:

\(\text{baseline}_{home}=\text{avg\_goals\_per\_game}_{home}=\frac{\sum_{i=1}^{20}\text{GF}_i}{19\cdot20}\approx1.568421\)

\(\text{baseline}_{away}=\text{avg\_goals\_per\_game}_{away}=\frac{\sum_{i=1}^{20}\text{GA}_i}{19\cdot20}\approx1.252632\)

Step 3:

According to the method outlined in the article, the expected goals for
a home team are:

\(\text{goals}=\text{baseline}_{home}\cdot\text{attack\_strength}_{home}\cdot\text{defence\_weakness}_{away}\)

And the expected goals of an away team are:

\(\text{goals}=\text{baseline}_{away}\cdot\text{attack\_strength}_{away}\cdot\text{defence\_weakness}_{home}\)

Step 4:

The goals scored by teams are modeled using a Poisson distribution,
based on the independence of each game, `attack strength' and `defence
weakness'. And the scores of a team do not give us additional
information about the performance of another team.

Firstly, the number of goals in a game \(\text{goals}\) is modeled as
\(\lambda\). Then, the probability \(P(X = x)\) represents the
likelihood of the target team scoring exactly \(x\) goals.

According to the Poisson distribution:

\(P(X=x)=\frac{\lambda^x}{x!}\cdot e^{-x}\)

Given that the goals scored by each team are independent, the joint
probability for a match is:

\(P(X=x,Y=y)=\frac{\lambda^x}{x!}\cdot e^{-x}\cdot\frac{\lambda^y}{y!}\cdot e^{-y}\)

\hypertarget{question-1-2}{%
\subsection{Question 1}\label{question-1-2}}

\end{document}
